apiVersion: v1

kind: Service

metadata:

  name: git-sync-service

spec:

  selector:

    app: my-app

  ports:

    - protocol: TCP

      port: 8090

      targetPort: 80

      nodePort: 30027

  type: NodePort